# Generated by Django 2.1.3 on 2018-12-14 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing.Product'),
        ),
    ]
